server:
    port: 8081

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://rds-prd-eximbay-seoul-eximbay-aurora.cluster-ro-c6242s4rjs3b.ap-northeast-2.rds.amazonaws.com:3307/EXIMBAY?useSSL=false&autoDeserialize=true&validationQuery=select 1&testWhileIdle=true&timeBetweenEvictionRunsMillis=600000
        username: WR_PGONLINE_SLV
        password: WrSlv$346105

    mail:
        host: smtp.gmail.com
        port: 587
        username: onlinesupport@eximbay.com  # Gmail 계정
        password: idkduyfkueatzfoo   # Gmail 비밀번호
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000

